---
- name: catalogue service configuration
  hosts: catalogue
  become: yes
  tasks: 
  - name: ansible disable old and enable nodejs:18
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y
  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present
  - name: user creation
    ansible.builtin.user:
      name: roboshop
  - name: create folder
    ansible.builtin.file:
      path: /app
      state: directory
      mode: '0755'
  - name: Download catalogue.zip
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp/catalogue.zip
      mode: '0440'
  - name: Extract /tmp/catalogue.zip into /app
    ansible.builtin.unarchive:
      src:   /tmp/catalogue.zip
      dest:  /app
      remote_src: yes

  - name: "Install packages based on package.json"
    npm:
      path: /app
  - name: "copy catalogue service content in /etc/systemd/system/catalogue.service"
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service
  - name: "deamon reloaded in shell manually"
    ansible.builtin.shell: systemctl deamon-reload
  - name: catalogue service enable and start
    ansible.builtin.service:
      name: catalogue
      enabled: yes
      state: started
  - name: copy mongo.repo file to /etc/yum.repos.d/mongo.repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo   

  

      

  
  

     
