- name: nginx install and Run
  hosts:  web
  become: true
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: Run nginx
    ansible.builtin.service:
      name:  nginx
      state: started

- name: cart install
  hosts: cart
  tasks:
  - name: nodejs install
    ansible.builtin.package:
     name: nodejs
     state: present
  - name: nodejs
    ansible.builtin.service:
     name: nodejs
     state: started



   