- name: nginx install and Run
  hosts:  web
  become: true
  tasks:
  - name: nginx
    ansible.builtin.package:
      name: nginx
      state: present
  -   name: Run nginx
      service: started 
   