- name: PLAY-1 nginx install and Run
  hosts:  web
  become: true
  tasks:
  - name: TASK-1 install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: TASK-2 Run nginx
    ansible.builtin.service:
      name:  nginx
      state: started
      enabled: yes






   